/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/layouts/Body/Home/Carousel.vue')['default']
    CartBody: typeof import('./src/layouts/Body/CartBody.vue')['default']
    Categories: typeof import('./src/layouts/Body/Home/Categories.vue')['default']
    CategoryBar: typeof import('./src/layouts/Body/Home/CategoryBar.vue')['default']
    CheckoutBody: typeof import('./src/layouts/Body/CheckoutBody.vue')['default']
    copy: typeof import('./src/layouts/Body/ProductDetailBody copy.vue')['default']
    CouponTabPanel: typeof import('./src/layouts/Body/UserDashboard/CouponTabPanel.vue')['default']
    Footer: typeof import('./src/layouts/Footer.vue')['default']
    Header: typeof import('./src/layouts/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeBody: typeof import('./src/layouts/Body/HomeBody.vue')['default']
    MenubarEnd: typeof import('./src/layouts/Header/MenubarEnd.vue')['default']
    NewAndHotProduction: typeof import('./src/layouts/Body/Home/NewAndHotProduction.vue')['default']
    OAuthLogin: typeof import('./src/layouts/Header/inMenubarEnd/OAuthLogin.vue')['default']
    OrderlistTabPanel: typeof import('./src/layouts/Body/UserDashboard/OrderlistTabPanel.vue')['default']
    ProductCarousel: typeof import('./src/layouts/Body/Home/ProductCarousel.vue')['default']
    ProductDetailBody: typeof import('./src/layouts/Body/ProductDetailBody.vue')['default']
    'ProductDetailBody copy': typeof import('./src/layouts/Body/ProductDetailBody copy.vue')['default']
    ProductList: typeof import('./src/layouts/Body/ProductDisplay/ProductList.vue')['default']
    ProductsDisplayBody: typeof import('./src/layouts/Body/ProductsDisplayBody.vue')['default']
    ProfileTabPanel: typeof import('./src/layouts/Body/UserDashboard/ProfileTabPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavbar: typeof import('./src/layouts/Body/ProductDisplay/SideNavbar.vue')['default']
    SpecialDeal: typeof import('./src/layouts/Body/Home/SpecialDeal.vue')['default']
    Subscription: typeof import('./src/layouts/Body/Home/Subscription.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserDashboardBody: typeof import('./src/layouts/Body/UserDashboardBody.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
