/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    Body: typeof import('./src/layouts/Body.vue')['default']
    Carousel: typeof import('./src/layouts/Body/Home/Carousel.vue')['default']
    Categories: typeof import('./src/layouts/Body/Home/Categories.vue')['default']
    Footer: typeof import('./src/layouts/Footer.vue')['default']
    Header: typeof import('./src/layouts/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeBody: typeof import('./src/layouts/Body/HomeBody.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    Icons: typeof import('./src/layouts/Header/Icons.vue')['default']
    LikeList: typeof import('./src/layouts/Header/LikeList.vue')['default']
    'LoginModal(直接用第三方登入取代)': typeof import('./src/layouts/Header/LoginModal(直接用第三方登入取代).vue')['default']
    Logo: typeof import('./src/layouts/Header/Logo.vue')['default']
    Nav: typeof import('./src/layouts/Header/Nav.vue')['default']
    NewAndHotProduction: typeof import('./src/layouts/Body/Home/NewAndHotProduction.vue')['default']
    ProductCarousel: typeof import('./src/layouts/Body/Home/ProductCarousel.vue')['default']
    ProductCategoryBody: typeof import('./src/layouts/Body/ProductCategoryBody.vue')['default']
    ProductDetailBody: typeof import('./src/layouts/Body/ProductDetailBody.vue')['default']
    ProductList: typeof import('./src/layouts/Body/ProductCategory/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavbar: typeof import('./src/layouts/Body/ProductCategory/SideNavbar.vue')['default']
    SpecialDeal: typeof import('./src/layouts/Body/Home/SpecialDeal.vue')['default']
    Subscription: typeof import('./src/layouts/Body/Home/Subscription.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    User: typeof import('./src/views/User.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
