import type { Product } from './type'

export const mockProducts: Product[] = [
  // ── 上半身 top ──────────────────────────────────────────
  {
    product_id: 'top-001',
    name: '白色合身毛衣',
    category: 'top',
    original_price: 1280,
    sale_price: 980,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542943815.jpg'],
    product_status: ['現貨', '新品'],
    stock: 18,
    average_rating: 4.7,
    description: '柔軟合身剪裁，百搭白色毛衣，適合各種場合穿搭。',
    created_at: new Date('2024-10-01'),
    updated_at: new Date('2024-11-15'),
  },
  {
    product_id: 'top-002',
    name: '細肩帶素色上衣',
    category: 'top',
    original_price: 680,
    sale_price: 680,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542949849.jpg'],
    product_status: ['現貨'],
    stock: 32,
    average_rating: 4.3,
    description: '輕薄透氣細肩帶設計，素色簡約風格，夏日必備單品。',
    created_at: new Date('2024-09-15'),
    updated_at: new Date('2024-10-20'),
  },
  {
    product_id: 'top-003',
    name: '大叔黑上衣',
    category: 'top',
    original_price: 890,
    sale_price: 750,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543681662.jpg'],
    product_status: ['現貨'],
    stock: 25,
    average_rating: 4.1,
    description: '寬鬆版型黑色上衣，慵懶街頭風格，男女皆宜。',
    created_at: new Date('2024-08-20'),
    updated_at: new Date('2024-09-10'),
  },
  {
    product_id: 'top-004',
    name: '潮流夾克',
    category: 'top',
    original_price: 2580,
    sale_price: 1980,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543685893.jpg'],
    product_status: ['現貨', '新品'],
    stock: 10,
    average_rating: 4.8,
    description: '街頭潮流夾克，多口袋設計，秋冬必備外搭單品。',
    created_at: new Date('2024-10-10'),
    updated_at: new Date('2024-11-01'),
  },
  {
    product_id: 'top-005',
    name: '黑色運動上衣',
    category: 'top',
    original_price: 780,
    sale_price: 580,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543694559.jpg'],
    product_status: ['現貨'],
    stock: 40,
    average_rating: 4.4,
    description: '吸濕排汗機能布料，修身剪裁，運動休閒兩用。',
    created_at: new Date('2024-07-01'),
    updated_at: new Date('2024-08-15'),
  },
  {
    product_id: 'top-006',
    name: '橘色上衣',
    category: 'top',
    original_price: 750,
    sale_price: 750,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543698693.jpg'],
    product_status: ['現貨', '限購'],
    stock: 8,
    average_rating: 4.2,
    description: '活力橘色調，寬鬆版型，為日常穿搭增添亮點。',
    created_at: new Date('2024-11-01'),
    updated_at: new Date('2024-11-20'),
  },

  // ── 下半身 bottom ────────────────────────────────────────
  {
    product_id: 'btm-001',
    name: '大白鵝長褲',
    category: 'bottom',
    original_price: 1180,
    sale_price: 880,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543647726.jpg'],
    product_status: ['現貨'],
    stock: 22,
    average_rating: 4.5,
    description: '寬鬆直筒版型，柔軟面料，舒適日常首選長褲。',
    created_at: new Date('2024-09-01'),
    updated_at: new Date('2024-10-05'),
  },
  {
    product_id: 'btm-002',
    name: '水藍瑜伽褲',
    category: 'bottom',
    original_price: 1080,
    sale_price: 880,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543652926.jpg'],
    product_status: ['現貨', '新品'],
    stock: 30,
    average_rating: 4.6,
    description: '高彈力瑜伽褲，水藍色系清新，運動瑜伽皆適用。',
    created_at: new Date('2024-10-15'),
    updated_at: new Date('2024-11-10'),
  },
  {
    product_id: 'btm-003',
    name: '蛇皮紋裙',
    category: 'bottom',
    original_price: 1380,
    sale_price: 1080,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543663159.jpg'],
    product_status: ['現貨', '限購'],
    stock: 6,
    average_rating: 4.3,
    description: '時尚蛇皮紋印花裙，個性十足，派對約會必備。',
    created_at: new Date('2024-11-05'),
    updated_at: new Date('2024-11-18'),
  },
  {
    product_id: 'btm-004',
    name: '勇敢牛仔褲',
    category: 'bottom',
    original_price: 1580,
    sale_price: 1280,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543672742.jpg'],
    product_status: ['現貨'],
    stock: 20,
    average_rating: 4.7,
    description: '經典直筒牛仔褲，耐穿耐洗，百搭日常必備款。',
    created_at: new Date('2024-08-01'),
    updated_at: new Date('2024-09-20'),
  },
  {
    product_id: 'btm-005',
    name: '牛仔套裝',
    category: 'bottom',
    original_price: 2280,
    sale_price: 1880,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542892800.jpg'],
    product_status: ['現貨', '新品'],
    stock: 12,
    average_rating: 4.5,
    description: '上下身牛仔套裝，復古水洗工藝，整套穿搭省心又時尚。',
    created_at: new Date('2024-10-20'),
    updated_at: new Date('2024-11-12'),
  },

  // ── 鞋 shoes ─────────────────────────────────────────────
  {
    product_id: 'shoes-001',
    name: '平價黑鞋',
    category: 'shoes',
    original_price: 980,
    sale_price: 780,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542875933.jpg'],
    product_status: ['現貨'],
    stock: 35,
    average_rating: 4.2,
    description: '簡約百搭黑色平底鞋，舒適好穿，上班通勤首選。',
    created_at: new Date('2024-07-15'),
    updated_at: new Date('2024-09-01'),
  },
  {
    product_id: 'shoes-002',
    name: '平價涼鞋',
    category: 'shoes',
    original_price: 880,
    sale_price: 680,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542899415.jpg'],
    product_status: ['現貨'],
    stock: 28,
    average_rating: 4.0,
    description: '輕便涼鞋設計，透氣舒適，夏日海邊或日常皆宜。',
    created_at: new Date('2024-06-01'),
    updated_at: new Date('2024-07-20'),
  },

  // ── 飾品 accessory ───────────────────────────────────────
  {
    product_id: 'acc-001',
    name: '埃及王后耳環',
    category: 'accessory',
    original_price: 580,
    sale_price: 480,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542939634.jpg'],
    product_status: ['現貨', '新品'],
    stock: 15,
    average_rating: 4.8,
    description: '埃及風格幾何耳環，金屬質感，為造型增添神秘氣息。',
    created_at: new Date('2024-11-01'),
    updated_at: new Date('2024-11-15'),
  },
  {
    product_id: 'acc-002',
    name: '舍利子手環',
    category: 'accessory',
    original_price: 780,
    sale_price: 680,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543677342.jpg'],
    product_status: ['現貨'],
    stock: 20,
    average_rating: 4.5,
    description: '天然石材手環，帶有禪意美感，日常配戴或送禮皆宜。',
    created_at: new Date('2024-09-10'),
    updated_at: new Date('2024-10-01'),
  },
  {
    product_id: 'acc-003',
    name: '黑色手銬',
    category: 'accessory',
    original_price: 480,
    sale_price: 380,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543689792.jpg'],
    product_status: ['現貨', '限購'],
    stock: 9,
    average_rating: 4.1,
    description: '金屬感黑色手環，個性龐克風格，搭配各種穿搭皆出色。',
    created_at: new Date('2024-10-25'),
    updated_at: new Date('2024-11-08'),
  },
  {
    product_id: 'acc-004',
    name: '黑色透明眼鏡',
    category: 'accessory',
    original_price: 680,
    sale_price: 580,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542933048.jpg'],
    product_status: ['現貨'],
    stock: 18,
    average_rating: 4.4,
    description: '透明鏡框黑色細節，文青知性風格，無度數裝飾眼鏡。',
    created_at: new Date('2024-08-10'),
    updated_at: new Date('2024-09-25'),
  },
  {
    product_id: 'acc-005',
    name: '原黑白表',
    category: 'accessory',
    original_price: 1280,
    sale_price: 980,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542919332.jpg'],
    product_status: ['現貨', '新品'],
    stock: 11,
    average_rating: 4.6,
    description: '極簡黑白配色腕錶，皮革錶帶，日常商務皆適合。',
    created_at: new Date('2024-11-10'),
    updated_at: new Date('2024-11-20'),
  },

  // ── 配件 life ────────────────────────────────────────────
  {
    product_id: 'life-001',
    name: '小白袋',
    category: 'life',
    original_price: 880,
    sale_price: 780,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542904018.jpg'],
    product_status: ['現貨'],
    stock: 24,
    average_rating: 4.3,
    description: '小巧白色手提袋，簡約設計，日常外出輕便好搭。',
    created_at: new Date('2024-09-05'),
    updated_at: new Date('2024-10-10'),
  },
  {
    product_id: 'life-002',
    name: '精美手拿包',
    category: 'life',
    original_price: 1480,
    sale_price: 1180,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542910032.jpg'],
    product_status: ['現貨', '新品'],
    stock: 13,
    average_rating: 4.7,
    description: '精緻手拿包，多夾層設計，晚宴派對或日常皆適用。',
    created_at: new Date('2024-10-18'),
    updated_at: new Date('2024-11-05'),
  },
  {
    product_id: 'life-003',
    name: '白色購物袋',
    category: 'life',
    original_price: 580,
    sale_price: 480,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542914365.jpg'],
    product_status: ['現貨'],
    stock: 50,
    average_rating: 4.0,
    description: '大容量白色帆布購物袋，環保耐用，日常採購好幫手。',
    created_at: new Date('2024-07-20'),
    updated_at: new Date('2024-08-30'),
  },
  {
    product_id: 'life-004',
    name: '死亡筆記本',
    category: 'life',
    original_price: 380,
    sale_price: 280,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777542924098.jpg'],
    product_status: ['現貨', '限購'],
    stock: 7,
    average_rating: 4.9,
    description: '經典黑色硬殼筆記本，內頁空白，書寫流暢，收藏必備。',
    created_at: new Date('2024-11-08'),
    updated_at: new Date('2024-11-18'),
  },
  {
    product_id: 'life-005',
    name: '迷途背包',
    category: 'life',
    original_price: 1980,
    sale_price: 1580,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543667875.jpg'],
    product_status: ['現貨', '新品'],
    stock: 16,
    average_rating: 4.6,
    description: '大容量多夾層後背包，防潑水材質，通勤旅行皆實用。',
    created_at: new Date('2024-10-28'),
    updated_at: new Date('2024-11-14'),
  },
  {
    product_id: 'life-006',
    name: '英國村婦套裝',
    category: 'life',
    original_price: 2880,
    sale_price: 2380,
    img_urls: ['https://kaoxjrxoqzygojubmmtf.supabase.co/storage/v1/object/public/product-images/1777543657359.jpg'],
    product_status: ['預購'],
    stock: 5,
    average_rating: 4.4,
    description: '英倫復古風格套裝，格紋設計，優雅知性氣質十足。',
    created_at: new Date('2024-11-15'),
    updated_at: new Date('2024-11-20'),
  },
]
