export const fakeProduct = [
  {
    name: '產品標題1',
    id: '001',
    description: '產品描述1',
    originalPrice: 1680,
    salePrice: 99,
    category: '種類1',
    ratings: 5,
    images: ['https://via.placeholder.com/150', 'https://via.placeholder.com/150'],
    quantity: 10,
    isLike: ref(false),
  },
  {
    name: '產品標題2',
    id: '002',
    description: '產品描述2',
    originalPrice: 1880,
    salePrice: 99,
    category: '種類2',
    ratings: 4,
    images: ['https://via.placeholder.com/150', 'https://via.placeholder.com/150'],
    quantity: 5,
    isLike: ref(true),
  },
  {
    name: '產品標題3',
    id: '003',
    description: '產品描述3',
    originalPrice: 1780,
    salePrice: 99,
    category: '種類3',
    ratings: 3,
    images: ['https://via.placeholder.com/150', 'https://via.placeholder.com/150'],
    quantity: 15,
    isLike: ref(false),
  },
  {
    name: '產品標題4',
    id: '004',
    description: '產品描述4',
    originalPrice: 1980,
    salePrice: 99,
    category: '種類4',
    ratings: 2,
    images: ['https://via.placeholder.com/150', 'https://via.placeholder.com/150'],
    quantity: 20,
    isLike: ref(true),
  },
]